version: "3"
services:
  add_user:
    build:
      context: ./src/add_user
      dockerfile: Dockerfile
    image: add_user:latest
    ports:
      - "5001:5001"

  hello_vijay:
    build:
      context: ./src/hello_vijay
      dockerfile: Dockerfile
    image: hello_vijay:latest
    ports:
      - "5003:5003"

  getbmi_by_id:
    build:
      context: ./src
      dockerfile: ./getbmi_by_id/Dockerfile
    image: getbmi_by_id:latest
    ports:
      - "5002:5002