service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: src/main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9.17
  stage: dev
  region: ap-southeast-1

functions:
  add_user_function:
    handler: wsgi.handler
    events:
      - http:
          path: add_user
          method: ANY

  get_bmi_function:
    handler: wsgi.handler
    events:
      - http:
          path: getBmi
          method: ANY
