name: ECR Deploy

on:
  push:
    branches:
      - dockerDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ecr-deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          services=('add_user' 'hello_vijay' 'getbmi_by_id')

          for service in "${services[@]}"; 
          do 
              docker-compose build "$service"
              docker tag "$service" "$ECR_REGISTRY/$service:$IMAGE_TAG"
              docker images
              echo "these are the current existing image"
              docker push "$ECR_REGISTRY/$service:$IMAGE_TAG"
              echo "$service has been pushed to $ECR_REGISTRY "
          done

#test for updated image
